import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/header";
import { CategoryProvider } from "@/context/CategoryContext"; // Adjust the path as necessary
import "@/css/globals.css"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CategoryProvider>
          <div id="wrapper">
            <main id="main">
              <div className="inner">
                <Header children={null} />
                {children}
              </div>
            </main>
            <Sidebar />
          </div>
        </CategoryProvider>
      </body>
    </html>
  );
}
