
import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import { useState } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [category, setCategory] = useState<number>(4);

  const updateCategory = (newCategory: number) => {
    setCategory(newCategory);
  };

  return (
    <html lang="en">
      <body>
        <div id="wrapper">
          <main id="main">{children}</main>
          <Sidebar changeCategoryName={updateCategory} />
        </div>
      </body>
    </html>
  );
}
